# Usaremos una imagen base oficial de Python
FROM python:3.10-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo de la aplicacion al contenedor
COPY app.py .

# Comando a ejecutar al inicar el contendor
CMD ["python","app.py"]
